### ISSUE TITLE
`Transaction.getSignatures()` throws error

### ISSUE THREAD

**Issue by danielakhterov** [hashgraph/hedera-sdk-js#327]
Add regression test for this.

**Comment by SimiHunjan** [comment]
If I use getSignatures() with the () after it, I get the following error: 

Code:
`console.log("View the 3 public keys that signed the transaction " +signedTransaction.getSignatures());`

Response:
`TypeError: Cannot read property 'sigMap' of undefined`

I assumed it was going to be the same as the method syntax used in Java with the '`()`' after `getSignatures`


I removed the '`()`' and used `.getSignatures`

Code: 
```
//Print all public keys that signed the transaction
    console.log("View the 3 public keys that signed the transaction " +signedTransaction.getSignatures)
```

Response:
```
View the 3 public keys that signed the transaction getSignatures() {
    return _SignatureMap.default._fromTransaction(this);
  }
```

**Comment by danielakhterov** [comment]
@SimiHunjan how did you sign the `Transaction`?
 - `Transaction.sign()`
 - `Transaction.signWith()`
 - Transaction.addSiganture()`
 - `Transaction.signWithOperator()`
 - `PrivateKey.signTransaction()`
Or did you simply do `getSignatures()` without signing the transaction?

**Comment by SimiHunjan** [comment]
Here is how I signed. The same steps I used in Java which worked fine.

Code:

  ```
  //Freeze the transaction
    const transaction = await transferTransaction.freezeWith(client);

    //Signer one signs the transaction with their private key
    const signature1 = privateKeySigner1.signTransaction(transaction);

    //Signer two signs the transaction with their private key
    const signature2 = privateKeySigner2.signTransaction(transaction);

    //Signer three signs the transaction with their private key
    const signature3 = privateKeySigner3.signTransaction(transaction);

    //The signature1, signature2, and signature3 are returned back to you

    //Collate all three signatures with the transaction
    const signedTransaction = transaction.addSignature(publicKey1, signature1).addSignature(publicKey2, signature2).addSignature(publicKey3, signature3);

    //Print all public keys that signed the transaction
    console.log("View the 3 public keys that signed the transaction " +signedTransaction.getSignatures);

```

**Comment by danielakhterov** [comment]
@SimiHunjan Also, to double check, you're on the latest JS release?

**Comment by SimiHunjan** [comment]
I am on v2.0.13

**Comment by danielakhterov** [comment]
I believe this is now fixed in v2.0.16. Added regression test here: https://github.com/hashgraph/hedera-sdk-js/blob/master/test/integration/TransactionIntegrationTest.js#L83

**Comment by SimiHunjan** [comment]
I updated to v2.0.16 and it still does not seem to be fixed. Console returns the following for `getSignatures()`:

```
View the 3 public keys that signed the transaction getSignatures() {
    return _SignatureMap.default._fromTransaction(this);
  }

```

Please run the below example and let me know what prints to your console for that line. Thanks!

```
const { Client, PrivateKey, KeyList,AccountId, PublicKey, AccountCreateTransaction,TransferTransaction, AccountBalanceQuery, Hbar, FileCreateTransaction} = require("@hashgraph/sdk");
require("dotenv").config();

async function main() {

    //Grab your Hedera testnet account ID and private key from your .env file
    const myAccountId = process.env.MY_ACCOUNT_ID;
    const myPrivateKey = process.env.MY_PRIVATE_KEY;

    // If we weren't able to grab it, we should throw a new error
    if (myAccountId == null ||
        myPrivateKey == null ) {
        throw new Error("Environment variables myAccountId and myPrivateKey must be present");
    }

    //Create a connection to the Hedera test network
    const client = Client.forTestnet();

    client.setOperator(myAccountId, myPrivateKey);

    //Generate 3 key pairs
    const privateKeySigner1 = await PrivateKey.generate();
    const publicKey1 = privateKeySigner1.publicKey;

    const privateKeySigner2 = await PrivateKey.generate();
    const publicKey2 = privateKeySigner2.publicKey;

    const privateKeySigner3 = await PrivateKey.generate();
    const publicKey3 = privateKeySigner3.publicKey;

    //Print the public keys to the console
    console.log("Public key 1 " + publicKey1);
    console.log("Public key 2 " + publicKey2);
    console.log("Public key 3 " + publicKey3);

    const publicKeyList = [];
    
    publicKeyList.push(publicKey1);
    publicKeyList.push(publicKey2);
    publicKeyList.push(publicKey3);

    console.log("The public key list is " + publicKeyList);

    const keys = new KeyList(publicKeyList);

    console.log("The keyList " + keys);

    //Create an account with a key list
    const transaction1 = new AccountCreateTransaction()
        // require 3 of the 3 keys we generated to sign future transactions that modify this account
        .setKey(keys)
        .setInitialBalance(new Hbar(10));

    //Submit the transaction to a Hedera network
    const txResponse = await transaction1.execute((client));

    //Get the receipt of the transaction
    const receipt = await txResponse.getReceipt(client);

    //Get the account ID from the receipt of the transaction
    const senderAccountId = receipt.accountId;

    console.log("The new account ID is " + senderAccountId);

    //The node account ID to submit the transaction to. You can add more than 1 node account ID

    const nodeId = [];
    nodeId.push(new AccountId(3));
    

    const receiverAccountId = myAccountId;

    //Create the transfer transaction
    const transferTransaction = new TransferTransaction()
        .addHbarTransfer(senderAccountId, new Hbar(1))
        .addHbarTransfer(receiverAccountId, new Hbar(-1))
        .setNodeAccountIds(nodeId);

    //Freeze the tranaction from further modifications
    const transaction = await transferTransaction.freezeWith(client);

    //Signer one signs the transaction with their private key
    const signature1 = privateKeySigner1.signTransaction(transaction);

    //Signer two signs the transaction with their private key
    const signature2 = privateKeySigner2.signTransaction(transaction);

    //Signer three signs the transaction with their private key
    const signature3 = privateKeySigner3.signTransaction(transaction);

    //The signature1, signature2, and signature3 are returned back to you

    //Collate all three signatures with the transaction
    const signedTransaction = transaction.addSignature(publicKey1, signature1).addSignature(publicKey2, signature2).addSignature(publicKey3, signature3);

    //Print all public keys that signed the transaction
    console.log("View the 3 public keys that signed the transaction " +signedTransaction.getSignatures);

    //Submit the transaction to a Hedera network
    const submitTx = await signedTransaction.execute(client);

    //Get the transaction ID
    const txId = submitTx.transactionId.toString();

    //Print the transaction ID to the console
    console.log(txId);

    }
main();
```
