### ISSUE TITLE
Included React-Native example builds and launches in simulator, but SDK calls fail

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-sdk-js#354]
I am unable to get the React Native example included with the JS-SDK version 2.0.19 on ios. Here are basically the command I ran:

```
yarn install
cd pod
pod install
cd ..
yarn start
yarn ios
```

The project was successfully built and launched in the simulator, but immediately failed with the following in the simulator:

```
TransactionId: Waiting for data
AccountInfo.accountId: Waiting for data
Balance: Waiting for data
Random Mnemonic: Waiting for data
```

and the following in the console:

```
To reload the app press "r"
To open developer menu press "d"

info Reloading app...
[Wed May 05 2021 08:43:39.550]  BUNDLE  ./index.js 

[Wed May 05 2021 08:44:01.366]  LOG      Running "main" with {"rootTag":21,"initialProps":{}}
[Wed May 05 2021 08:44:01.474]  WARN     Possible Unhandled Promise Rejection (id: 0):
TypeError: null is not an object (evaluating '_ExpoRandom.default.getRandomBytesAsync')
getRandomBytesAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126213:37
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29602:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4382:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4546:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4405:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29601:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29606:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29623:69
getRandomBytesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126206:38
bytesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126163:38
_generate$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119626:68
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29602:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4382:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4546:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4405:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29601:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29606:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29623:69
_generate@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119598:42
generate12@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119592:34
componentDidMount@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:114632:33
commitLifeCycles@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:24220:47
commitLayoutEffects@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26480:29
invokeGuardedCallbackImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13701:21
invokeGuardedCallback@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13795:42
commitRootImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26269:36
commitRootImpl@[native code]
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:48413:30
commitRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26156:24
performSyncWorkOnRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25680:19
performSyncWorkOnRoot@[native code]
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16952:38
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:48413:30
flushSyncCallbackQueueImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16947:28
flushSyncCallbackQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16936:35
scheduleUpdateOnFiber@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25289:37
updateContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:27768:21
render@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:28202:24
renderApplication@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:75853:77
run@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:75427:28
runApplication@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:75480:28
__callFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3690:36
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3422:31
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3421:21
callFunctionReturnFlushedQueue@[native code]
[Wed May 05 2021 08:44:01.770]  WARN     Possible Unhandled Promise Rejection (id: 1):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:44:01.846]  WARN     Possible Unhandled Promise Rejection (id: 2):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:44:01.904]  WARN     Possible Unhandled Promise Rejection (id: 3):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:00.180]  WARN     Possible Unhandled Promise Rejection (id: 4):
TypeError: null is not an object (evaluating '_ExpoRandom.default.getRandomBytesAsync')
getRandomBytesAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126213:37
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29602:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4382:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4546:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4405:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29601:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29606:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29623:69
getRandomBytesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126206:38
bytesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126163:38
_generate$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119626:68
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29602:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4382:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4546:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4405:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29601:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29606:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29623:69
_generate@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119598:42
generate12@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119592:34
componentDidMount@http://localhost:8081/App.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:91:33
commitLifeCycles@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:24220:47
commitLayoutEffects@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26480:29
invokeGuardedCallbackImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13701:21
invokeGuardedCallback@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13795:42
commitRootImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26269:36
commitRootImpl@[native code]
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:48413:30
commitRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26156:24
performSyncWorkOnRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25680:19
performSyncWorkOnRoot@[native code]
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16952:38
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:48413:30
flushSyncCallbackQueueImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16947:28
flushSyncCallbackQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16936:35
flushSync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25718:33
scheduleRefresh@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:17575:20
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:45944:38
forEach@[native code]
performReactRefresh@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:45936:31
performReactRefresh@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:45741:48
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:484:40
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
callTimers@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31730:19
__callFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3690:36
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3422:31
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3421:21
callFunctionReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:00.432]  WARN     Possible Unhandled Promise Rejection (id: 5):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:00.433]  WARN     Possible Unhandled Promise Rejection (id: 6):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:00.434]  WARN     Possible Unhandled Promise Rejection (id: 7):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:10.897]  WARN     Possible Unhandled Promise Rejection (id: 8):
TypeError: null is not an object (evaluating '_ExpoRandom.default.getRandomBytesAsync')
getRandomBytesAsync$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126213:37
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29602:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4382:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4546:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4405:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29601:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29606:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29623:69
getRandomBytesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126206:38
bytesAsync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:126163:38
_generate$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119626:68
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29602:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4382:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4546:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4405:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29601:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29606:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29623:69
_generate@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119598:42
generate12@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:119592:34
componentDidMount@http://localhost:8081/App.bundle?platform=ios&dev=true&minify=false&modulesOnly=true&runModule=false&shallow=true:91:33
commitLifeCycles@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:24220:47
commitLayoutEffects@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26480:29
invokeGuardedCallbackImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13701:21
invokeGuardedCallback@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13795:42
commitRootImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26269:36
commitRootImpl@[native code]
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:48413:30
commitRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:26156:24
performSyncWorkOnRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25680:19
performSyncWorkOnRoot@[native code]
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16952:38
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:48413:30
flushSyncCallbackQueueImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16947:28
flushSyncCallbackQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:16936:35
flushSync@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25718:33
scheduleRefresh@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:17575:20
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:45944:38
forEach@[native code]
performReactRefresh@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:45936:31
performReactRefresh@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:45741:48
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:484:40
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
callTimers@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31730:19
__callFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3690:36
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3422:31
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3421:21
callFunctionReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:11.630]  WARN     Possible Unhandled Promise Rejection (id: 9):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:11.640]  WARN     Possible Unhandled Promise Rejection (id: 10):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Wed May 05 2021 08:53:11.780]  WARN     Possible Unhandled Promise Rejection (id: 11):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127152:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158878:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158663:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```

**Comment by danielakhterov** [comment]
Thanks for opening another issue, I was not getting notified with the mentions in the closed issue for some reason. I'll try running the react native example to see if it's still working. Unfortunately I cannot test using an iOS device though. One thing to note though is the way I have been testing is by running `yarn web` and then scanning the QR code with my phone while in the Expo App. Even while testing with Android I would do this instead of `yarn android`.

**Comment by danielakhterov** [comment]
I can confirm on my end that doing `rm -rf node_modules && yarn && yarn web` then scanning the QR code through the Expo App on my phone does work. As for getting the example working without the use of Expo, that's another beast.

**Comment by robkainz** [comment]
Hey @danielakhterov, my understanding is that React Native and React are two separate frameworks - one is for running mobile apps and the other for web apps. Just because an application runs on the React web platform does not mean that it will run on React Native. So there may be some incompatibilities in the libraries that the Hedera JS-SDK depends on and those that the React Native platform uses for example, causing you issues that you normally wouldn't see in React web applications. You should see the same failures that I see even if running it on an Android simulator using Android Studio. If you need me to do that with the latest version, I can also run it there to confirm. That's where I originally ran the 2.0.17 beta versions and got the same errors.

**Comment by danielakhterov** [comment]
@robkainz I understand that `React` != `React Native`. I run `yarn web` because I allows me to check both the performance of the SDK in a browser through `React` and on my Android phone through `React Native` using `Expo`. Perhaps I'm misunderstanding, but I'd assume that if I load the application on my phone through the `Expo` app it is natively running on my phone, and not in some hidden browser in the `Expo` app. When I was testing I was getting errors related to fetching random bytes _only on my phone_ which makes me think that the example is in fact running natively on my phone instead of some hidden browser. When I updated the SDK to use `Expo`'s `Random` package the example began to run on my phone correctly without errors. I'll need to dive further into getting and Android simulator running, but it seems weird that I am able to run the example on my phone, but not an Android simulator.

**Comment by danielakhterov** [comment]
@robkainz
I believe I've fixed the issue with the Android Emulator not working and pushed to `master`. Can you confirm this fix works for you as well?

**Comment by robkainz** [comment]
@danielakhterov 

Unfortunately I still see errors - I am running this currently on the IOS simulator (can try the Android one next). Here's the output for the app:

```
TransactionId: Waiting for data
AccountInfo.accountId: Waiting for data
Balance: Waiting for data
Random Mnemonic: north rotate grunt sight erupt jazz void sudden hair sun hour token

```
And below are the warnings/errors from the console log:

```
To reload the app press "r"
To open developer menu press "d"

[Mon May 17 2021 16:16:30.780]  BUNDLE  ./index.js 

[Mon May 17 2021 16:16:51.686]  LOG      Running "main" with {"rootTag":1,"initialProps":{}}
[Mon May 17 2021 16:16:52.950]  WARN     Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127274:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:159018:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158803:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Mon May 17 2021 16:16:52.195]  WARN     Possible Unhandled Promise Rejection (id: 1):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127274:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:159018:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158803:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
[Mon May 17 2021 16:16:52.243]  WARN     Possible Unhandled Promise Rejection (id: 2):
TypeError: undefined is not an object (evaluating 'asc.replace')
atobPolyfill@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:127274:16
decode@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:159018:45
_callee$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158803:49
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29672:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29499:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29572:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29582:21
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4373:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:4474:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31522:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31561:17
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:31778:33
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3661:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3447:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3644:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3446:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```

**Comment by danielakhterov** [comment]
Hmm, I'm that's interesting that `Mnemonic.generate()` worked, but the other calls did not. I'm looking at the error from the iOS simulator, and I'm not sure what it is complaining about and/or from where the error is being thrown. Unfortunately, I can't really test the example with on iOS Simulator because I don't have any iOS device.

**Comment by robkainz** [comment]
Ok, found some time and I stepped through using the React Native debugger on IOS and believe the issue is with this line in the Hedera SDK's NativeChannel.js:

```
const responseBuffer = base64.decode(
    responseData.split("data:application/octet-stream;base64,")[1]  //<=== line 65, NativeChannel.js
);
```
The function cannot decode because the split function returns an undefined object. The reason is because the string being decoded is not octet-stream, but instead:

> data:application/grpc-web+proto;base64,AAAAAACAAAAAD2dycGMtc3RhdHVzOjANCg=="

I'm hoping to get back to Wallawallet token service work next week, so it would be great if you guys had a fix for this by then. Thanks!

**Comment by danielakhterov** [comment]
@robkainz I can probably add a bandage fix for this before next week, but I'm so confused on why I am/was getting `application/octet-stream` while you're getting `application/grpc-web+proto`. Do you have any idea why this is?

**Comment by robkainz** [comment]
Honestly, not 100% sure why that is yet without digging into it deeper. It could be different for the different platforms, react-web vs react-native (for mobile devices) as I know you can't run it on an IOS device, so you're likely using react-web. But that may not explain why it is working for Android.

Your master branch example is incomplete in the react-native-example directory (missing package.json among other files.) If you can fix that I can try it out.

**Comment by danielakhterov** [comment]
I'm not sure if you noticed, but we moved the react native example into `./examples/react-native` to keep the examples in a single directory.

**Comment by robkainz** [comment]
FYI, in order to get "yarn install" working, I had to change this dependency path for the sdk in package.json:

`"@hashgraph/sdk": "file:../..",`

I also got this stack error in my react native console when trying to run the app, so looks like some kind of resolution issue:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:626:3)
    at tryReadSync (node:fs:391:20)
    at Object.readFileSync (node:fs:428:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/robertkainz/Development/hedera-sdk-js/examples/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/Users/robertkainz/Development/hedera-sdk-js/examples/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/Users/robertkainz/Development/hedera-sdk-js/examples/react-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/Users/robertkainz/Development/hedera-sdk-js/examples/react-native/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /Users/robertkainz/Development/hedera-sdk-js/examples/react-native/node_modules/metro/src/lib/transformHelpers.js:271:42
    at Server.<anonymous> (/Users/robertkainz/Development/hedera-sdk-js/examples/react-native/node_modules/metro/src/Server.js:842:41)
    at Generator.next (<anonymous>)
```

**Comment by danielakhterov** [comment]
@robkainz I've tested this today against an iOS simulator and it seems to be working fine. I've pushed a fix for the directory change you mentioned above, but running against an iOS simulator I was able to see all results. 
![image](https://user-images.githubusercontent.com/36461294/121618562-d451f200-ca1b-11eb-8696-7e1790539d10.png)

**Comment by danielakhterov** [comment]
What are the version of the following do you use?
 - iOS
 - Mac
 - Node
 - yarn
 - cocoapods
 - XCode

**Comment by robkainz** [comment]
Great work - thanks Daniel! I just grabbed master and confirmed the react native example works. Here's what I'm using:

Mac: 11.3.1
iOS: 13.2
Node: 16.0.0
yarn: 1.22.4
pod: 1.9.3
xCode: 12.5

Sometime next week I will plan to swap out the golang sdk for js sdk for Wallawallet and will let you know if I have any problems.

**Comment by mehcode** [comment]
Good to hear. I'm going to close this. It sounds like things are working for now.
